''' =========================================================================
    posts_xml_to_json

    This file will read in a posts.xml file (generated by dumping the XML
    of a SQLite DB (e.g., from Firefox SQLite manager) and convert
    it to a JSON file, which will be used by mongo
    ========================================================================='''
import json
import xmldict

''' =========================================================================

    Functions

    ========================================================================='''
def convert():
    '''Loads the posts.xml file, converts to JSON, and saves it'''

    #Load the posts file, make sure it exists
    try:
        posts = open('vasir_blog_post.xml')
    except IOError:
        print 'No posts.xml file defined! Make sure posts.xml exists'
        return False

    #Read the file
    posts = posts.read()
    
    #Convert the sucker
    posts_dict = xmldict.xml_to_dict(posts)

    #Prepare json file
    json_file = open('posts.json', 'w')

    #Get the posts
    posts = posts_dict['database']['table']

    #MongoDB expects the JSON file to have one document per line, so we need to
    #   iterate over each line in the file
    for card in posts:
        #Create an object from the existing one
        temp_post = {}
        temp_post['slug'] = card['column'][0]['#text']
        temp_post['title'] = card['column'][1]['#text']
        temp_post['post_date'] = card['column'][2]['#text']
        temp_post['post_last_edit_date'] = card['column'][3]['#text']
        temp_post['category'] = card['column'][6]['#text']
        temp_post['content'] = card['column'][7]['#text']
        temp_post['description'] = card['column'][8]['#text']

        #Save it
        json_file.write(json.dumps(temp_post) + '\n')

    #close it
    json_file.close()

    return True


''' =========================================================================

    Init / Main

    ========================================================================='''
if __name__ == '__main__':
    #Run it!
    print "Started conversion process..."
    convert()
    print "Done! posts.json file created"
